#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Translation\Command\XliffLintCommand;

require_once __DIR__ . '/vendor/autoload.php';

(new Application())
    ->add($command = new XliffLintCommand())
    ->getApplication()
    ->setDefaultCommand('lint:xliff', true)
    ->run();
