name: Lint
on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4

            -   name: Install dependencies
                run: composer install

            -   name: Lint
                run: ./lint ./invalid.en.xml
